FROM mongo

ARG MONGO_USER
ARG MONGO_PASSWORD
ARG MONGO_DATABASE

COPY ./init-mongo.js /docker-entrypoint-initdb.d
RUN sed --in-place "s/<MONGO_USER>/${MONGO_USER}/g" /docker-entrypoint-initdb.d/init-mongo.js
RUN sed --in-place "s/<MONGO_PASSWORD>/${MONGO_PASSWORD}/g" /docker-entrypoint-initdb.d/init-mongo.js
RUN sed --in-place "s/<MONGO_DATABASE>/${MONGO_DATABASE}/g" /docker-entrypoint-initdb.d/init-mongo.js
RUN cat /docker-entrypoint-initdb.d/init-mongo.js
