version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0.23
    restart: always
    env_file:
      - .env
    volumes:
      - /tmp/db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.0
    restart: always
    depends_on:
      - db

  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      args:
        - GUNICORN_INTERNAL_PORT=$GUNICORN_INTERNAL_PORT
        - NGINX_INTERNAL_PORT_APP=$NGINX_INTERNAL_PORT_APP
        - NGINX_INTERNAL_PORT_ADMINER=$NGINX_INTERNAL_PORT_ADMINER
    restart: always
    ports:
      - 0.0.0.0:$NGINX_EXTERNAL_PORT_APP:$NGINX_INTERNAL_PORT_APP
      - 0.0.0.0:$NGINX_EXTERNAL_PORT_ADMINER:$NGINX_INTERNAL_PORT_ADMINER
    depends_on:
      - app
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
